### ISSUE TITLE
Duplicated links in different pages

### ISSUE THREAD

**Issue by kuy** [markerikson/redux-ecosystem-links#31]
Thanks for merging #30 .
BTW, does redux-ecosystem-links allow duplicated links in different pages?  
I wanted to add `redux-saga-router` to `routing.md` page but I noticed it's already listed in `side-effects.md` page.

**Comment by markerikson** [comment]
Eh, I try to keep links in just one spot.  It can be a bit tough to decide sometimes, like with your example - is it really about "side effects", or is it about "routing"?  Is it better to list undo/redo libraries by intent ("undo/redo"), or implementation type (reducer vs store enhancer)?  I'll freely admit some of my decisions are kind of arbitrary, but hopefully I'm at least consistent with them.

If you feel that `redux-saga-router` is more accurately placed in "Routing" instead of "Side Effects", please go ahead and file a PR to move it over.

And while we're at it, I'll also say I'm interested in any offers/attempts to help improve the organization of this list or my React/Redux links list, and if you or anyone were to submit PRs that refactor the structure of the list, I'd definitely be interested.  For example, right now the "Side Effects" page is pretty cluttered, and I figure it'd be nice to split it up - say, maybe into "Generators", "Observables", "Other", etc, or splitting up the "Middleware" page into separate pages.

**Comment by kuy** [comment]
Great, thanks for a long answer. I could understand how you want to organize bunch of links. Umm... it is a difficult problem but I feel that the actual structure of "Side Effects" is reasonable now. If I move `redux-saga-router` to "Router" page, it will break the consistency.
