### ISSUE TITLE
Reducer as map of functions

### ISSUE THREAD

**Issue by NugzarGaguliya** [markerikson/redux-ecosystem-links#74]
I find createReducer function in documentation https://redux.js.org/recipes/reducing-boilerplate#reducers

```javascript
export function createReducer(initialState, handlers) {
  return (state = initialState, action) => {
    if (handlers.hasOwnProperty(action.type)) {
      return handlers[action.type](state, action);
    }
    return state;
  };
}
```
Is it any package in npm where i can refer in my app or I need to add this function in all projects and add link to this documentation?

**Comment by NugzarGaguliya** [comment]
found https://github.com/markerikson/redux-starter-kit

**Comment by markerikson** [comment]
There's also _many_ other similar options - see https://github.com/markerikson/redux-ecosystem-links/blob/master/reducers.md#reducer-utilities .

**Comment by markerikson** [comment]
@NugzarGaguliya : not this list in its current form, no, because it's all just Markdown text files.

However, there's an app being built that will parse this list and present it in a sortable form, at https://github.com/wilbertliu/redux-ecosystem .  It's not done yet, but I _think_ it's getting close.
